## Data from World Happiness Report

The World Happiness Report is an annual publication of the United Nations Sustainable Development Solutions Network. It contains articles, and rankings of national happiness based on respondent ratings of their own lives, which the report also correlates with various life factors.

In this notebook we will explore the happiness of different countries and the features associated.
The datasets that we will use are available in *Data*: **happiness2020.pkl** and **countries_info.csv**.

Although the features are self-explanatory, here a summary: 

**happiness2020.pkl**
* country: *Name of the country*
* happiness_score: *Happiness score*
* social_support: *Social support (mitigation the effects of inequality)*
* healthy_life_expectancy: *Healthy Life Expectancy*
* freedom_of_choices: *Freedom to make life choices*
* generosity: *Generosity (charity, volunteers)*
* perception_of_corruption: *Corruption Perception*
* world_region: *Area of the world of the country*

**countries_info.csv**
* country_name: *Name of the country*
* area: *Area in sq mi*
* population: *Number of people*
* literacy: *Literacy percentage*

In [1]:
!head Data/countries_info.csv

country_name,area,population,literacy
afghanistan,647500,31056997,"36,0"
albania,28748,3581655,"86,5"
algeria,2381740,32930091,"70,0"
argentina,2766890,39921833,"97,1"
armenia,29800,2976372,"98,6"
australia,7686850,20264082,"100,0"
austria,83870,8192880,"98,0"
azerbaijan,86600,7961619,"97,0"
bahrain,665,698585,"89,1"

In [2]:
import pandas as pd
%matplotlib inline

DATA_FOLDER = 'Data/'

HAPPINESS_DATASET = DATA_FOLDER+"happiness2020.csv"
COUNTRIES_DATASET = DATA_FOLDER+"countries_info.csv"

## Task 1: Load the data

Load the 2 datasets in Pandas dataframes (called *happiness* and *countries*), and show the first rows.


**Hint**: Use the correct reader and verify the data has the expected format.

In [21]:
# Write your code here

happiness = pd.read_csv(HAPPINESS_DATASET, sep=',')
happiness

,country,happiness_score,social_support,healthy_life_expectancy,freedom_of_choices,generosity,perception_of_corruption,world_region
0,Afghanistan,2.5669,0.470367,52.590000,0.396573,-0.096429,0.933687,South Asia
1,Albania,4.8827,0.671070,68.708138,0.781994,-0.042309,0.896304,Central and Eastern Europe
2,Algeria,5.0051,0.803385,65.905174,0.466611,-0.121105,0.735485,Middle East and North Africa
3,Argentina,5.9747,0.900568,68.803802,0.831132,-0.194914,0.842010,Latin America and Caribbean
4,Armenia,4.6768,0.757479,66.750656,0.712018,-0.138780,0.773545,Commonwealth of Independent States
...,...,...,...,...,...,...,...,...
130,Venezuela,5.0532,0.890408,66.505341,0.623278,-0.169091,0.837038,Latin America and Caribbean
131,Vietnam,5.3535,0.849987,67.952736,0.939593,-0.094533,0.796421,Southeast Asia
132,Yemen,3.5274,0.817981,56.727283,0.599920,-0.157735,0.800288,Middle East and North Africa
133,Zambia,3.7594,0.698824,55.299377,0.806500,0.078037,0.801290,Sub-Saharan Africa
134,Zimbabwe,3.2992,0.763093,55.617260,0.711458,-0.072064,0.810237,Sub-Saharan Africa

In [20]:
countries = pd.read_csv(COUNTRIES_DATASET, sep=',')
countries

    country_name     area  population literacy
0    afghanistan   647500    31056997     36,0
1        albania    28748     3581655     86,5
2        algeria  2381740    32930091     70,0
3      argentina  2766890    39921833     97,1
4        armenia    29800     2976372     98,6
..           ...      ...         ...      ...
130    venezuela   912050    25730435     93,4
131      vietnam   329560    84402966     90,3
132        yemen   527970    21456188     50,2
133       zambia   752614    11502010     80,6
134     zimbabwe   390580    12236805     90,7

[135 rows x 4 columns]

## Task 2: Let's merge the data

Create a dataframe called *country_features* by merging *happiness* and *countries*. A row of this dataframe must describe all the features that we have about a country.

**Hint**: Verify to have all the rows in the final dataframe

In [23]:
# Write your code here

merged_df = pd.merge(happiness, countries, right_index=True, left_index=True)
merged_df.drop(columns=['country_name'])
merged_df.head()

,country,happiness_score,social_support,healthy_life_expectancy,freedom_of_choices,generosity,perception_of_corruption,world_region,country_name,area,population,literacy
0,Afghanistan,2.5669,0.470367,52.590000,0.396573,-0.096429,0.933687,South Asia,afghanistan,647500,31056997,"36,0"
1,Albania,4.8827,0.671070,68.708138,0.781994,-0.042309,0.896304,Central and Eastern Europe,albania,28748,3581655,"86,5"
2,Algeria,5.0051,0.803385,65.905174,0.466611,-0.121105,0.735485,Middle East and North Africa,algeria,2381740,32930091,"70,0"
3,Argentina,5.9747,0.900568,68.803802,0.831132,-0.194914,0.842010,Latin America and Caribbean,argentina,2766890,39921833,"97,1"
4,Armenia,4.6768,0.757479,66.750656,0.712018,-0.138780,0.773545,Commonwealth of Independent States,armenia,29800,2976372,"98,6"

## Task 3: Where do people are happier?

Print the top 10 countries based on their happiness score (high is better).

In [26]:
# Write your code here

merged_df[['country','happiness_score']].sort_values(ascending=False, by=['happiness_score']).head(10)

         country  happiness_score
38       Finland           7.8087
31       Denmark           7.6456
115  Switzerland           7.5599
50       Iceland           7.5045
92        Norway           7.4880
87   Netherlands           7.4489
114       Sweden           7.3535
88   New Zealand           7.2996
6        Austria           7.2942
72    Luxembourg           7.2375

We are interested to know in what world region the people are happier. 

Create and print a dataframe with the (1) average happiness score and (2) the number of contries for each world region.
Sort the result to show the happiness ranking.

In [40]:
# Write your code here


average_happiness_df = merged_df[['world_region', 'country','happiness_score']].groupby('world_region').agg(['count','mean'])
average_happiness_df

                                   happiness_score
                                             count      mean
world_region
Central and Eastern Europe                      14  5.891393
Commonwealth of Independent States              12  5.358342
East Asia                                        3  5.483633
Latin America and Caribbean                     20  5.971280
Middle East and North Africa                    16  5.269306
North America and ANZ                            4  7.173525
South Asia                                       6  4.355083
Southeast Asia                                   8  5.517788
Sub-Saharan Africa                              32  4.393856
Western Europe                                  20  6.967405

In [41]:
grouped_merged_df = merged_df.groupby('world_region')
for world_region, country in grouped_merged_df:
    print('world_region', world_region)
    print('country', country)

world_region Central and Eastern Europe
country             country  happiness_score  social_support  healthy_life_expectancy  \
1           Albania           4.8827        0.671070                68.708138
16         Bulgaria           5.1015        0.937840                66.803978
28          Croatia           5.5047        0.874624                70.214905
30   Czech Republic           6.9109        0.914431                70.047935
36          Estonia           6.0218        0.934730                68.604958
49          Hungary           6.0004        0.921934                67.609970
66           Latvia           5.9500        0.918289                66.807465
71        Lithuania           6.2155        0.926107                67.294075
73        Macedonia           5.1598        0.820392                67.504425
98           Poland           6.1863        0.874257                69.311134
100         Romania           6.1237        0.825162                67.207237
105          Serbia           5.7782        0.881476                68.210205
108        Slovakia           6.2806        0.922494                68.906342
109        Slovenia           6.3634        0.939576                71.102989

     freedom_of_choices  generosity  perception_of_corruption  \
1              0.781994   -0.042309                  0.896304
16             0.745178   -0.143908                  0.935585
28             0.714839   -0.128538                  0.916495
30             0.818537   -0.230862                  0.858446
36             0.877709   -0.111698                  0.623074
49             0.718965   -0.194323                  0.892917
66             0.671238   -0.186889                  0.795580
71             0.747381   -0.219725                  0.809584
73             0.738841   -0.019877                  0.897491
98             0.862056   -0.205084                  0.686927
100            0.842823   -0.197815                  0.934300
105            0.726496   -0.073676                  0.843509
108            0.749953   -0.124409                  0.918096
109            0.936143   -0.080603                  0.817071

                   world_region    country_name    area  population literacy
1    Central and Eastern Europe         albania   28748     3581655     86,5
16   Central and Eastern Europe        bulgaria  110910     7385367     98,6
28   Central and Eastern Europe         croatia   56542     4494749     98,5
30   Central and Eastern Europe  czech republic   78866    10235455     99,9
36   Central and Eastern Europe         estonia   45226     1324333     99,8
49   Central and Eastern Europe         hungary   93030     9981334     99,4
66   Central and Eastern Europe          latvia   64589     2274735     99,8
71   Central and Eastern Europe       lithuania   65200     3585906     99,6
73   Central and Eastern Europe       macedonia   25333     2050554      NaN
98   Central and Eastern Europe          poland  312685    38536869     99,8
100  Central and Eastern Europe         romania  237500    22303552     98,4
105  Central and Eastern Europe          serbia   88361     9396411     93,0
108  Central and Eastern Europe        slovakia   48845     5439448      NaN
109  Central and Eastern Europe        slovenia   20273     2010347     99,7
world_region Commonwealth of Independent States
country           country  happiness_score  social_support  healthy_life_expectancy  \
4         Armenia           4.6768        0.757479                66.750656
7      Azerbaijan           5.1648        0.819308                65.508400
10        Belarus           5.5399        0.906747                66.104332
41        Georgia           4.6726        0.629033                64.495209
61     Kazakhstan           6.0579        0.934745                64.609962
64     Kyrgyzstan           5.5415        0.887228                64.106010
82        Moldova           5.6075        0.843314                65.013016
101        Russia           5.5460        0.903151                64.100456
116    Tajikistan           5.5557        0.835297                64.104591
122  Turkmenistan           5.1191        0.958966                62.211708
124       Ukraine           4.5607        0.878879                64.606781
129    Uzbekistan           6.2576        0.926596                65.107574

     freedom_of_choices  generosity  perception_of_corruption  \
4              0.712018   -0.138780                  0.773545
7              0.786824   -0.240255                  0.552538
10             0.639163   -0.164927                  0.635712
41             0.801642   -0.228920                  0.665945
61             0.811602   -0.068489                  0.764491
64             0.909375    0.154772                  0.888396
82             0.721609   -0.037741                  0.913314
101            0.729893   -0.151154                  0.864803
116            0.831383   -0.025089                  0.592076
122            0.826457    0.187672                  0.883692
124            0.663082   -0.030934                  0.920637
129            0.974998    0.248427                  0.501497

                           world_region  country_name      area  population  \
4    Commonwealth of Independent States       armenia     29800     2976372
7    Commonwealth of Independent States    azerbaijan     86600     7961619
10   Commonwealth of Independent States       belarus    207600    10293011
41   Commonwealth of Independent States       georgia     69700     4661473
61   Commonwealth of Independent States    kazakhstan   2717300    15233244
64   Commonwealth of Independent States    kyrgyzstan    198500     5213898
82   Commonwealth of Independent States       moldova     33843     4466706
101  Commonwealth of Independent States        russia  17075200   142893540
116  Commonwealth of Independent States    tajikistan    143100     7320815
122  Commonwealth of Independent States  turkmenistan    488100     5042920
124  Commonwealth of Independent States       ukraine    603700    46710816
129  Commonwealth of Independent States    uzbekistan    447400    27307134

    literacy
4       98,6
7       97,0
10      99,6
41      99,0
61      98,4
64      97,0
82      99,1
101     99,6
116     99,4
122     98,0
124     99,7
129     99,3
world_region East Asia
country      country  happiness_score  social_support  healthy_life_expectancy  \
24     China           5.1239        0.798761                69.289192
59     Japan           5.8708        0.883546                75.000969
83  Mongolia           5.4562        0.937142                62.304485

    freedom_of_choices  generosity  perception_of_corruption world_region  \
24            0.898518   -0.181426                  0.753971    East Asia
59            0.809961   -0.246910                  0.654558    East Asia
83            0.693351    0.098094                  0.863511    East Asia

   country_name     area  population literacy
24        china  9596960  1313973713     90,9
59        japan   377835   127463611     99,0
83     mongolia  1564116     2832224     97,8
world_region Latin America and Caribbean
country                 country  happiness_score  social_support  \
3             Argentina           5.9747        0.900568
13              Bolivia           5.7475        0.803109
15               Brazil           6.3756        0.896724
23                Chile           6.2285        0.879714
25             Colombia           6.1634        0.884440
27           Costa Rica           7.1214        0.901546
32   Dominican Republic           5.6892        0.882085
33              Ecuador           5.9252        0.836419
35          El Salvador           6.3483        0.806092
45            Guatemala           6.3989        0.816621
47                Haiti           3.7208        0.593248
48             Honduras           5.9532        0.821870
58              Jamaica           5.8898        0.915702
81               Mexico           6.4650        0.838665
89            Nicaragua           6.1371        0.857497
94               Panama           6.3048        0.902094
95             Paraguay           5.6921        0.898728
96                 Peru           5.7968        0.831075
128             Uruguay           6.4401        0.922811
130           Venezuela           5.0532        0.890408

     healthy_life_expectancy  freedom_of_choices  generosity  \
3                  68.803802            0.831132   -0.194914
13                 63.600471            0.875873   -0.091681
15                 66.480164            0.799805   -0.101812
23                 69.900620            0.744896   -0.065668
25                 67.699585            0.836180   -0.161236
27                 71.299850            0.934739   -0.102430
32                 65.807487            0.866203   -0.131263
33                 68.500038            0.859829   -0.127015
35                 66.108261            0.833805   -0.121073
45                 64.808945            0.908148   -0.042939
47                 55.598625            0.537825    0.400535
48                 67.198769            0.870603    0.086969
58                 67.099998            0.858069   -0.125107
81                 68.299026            0.858709   -0.175267
89                 67.507179            0.863903    0.020959
94                 69.603012            0.880367   -0.153928
95                 65.639938            0.885923    0.007998
96                 68.100235            0.824766   -0.162388
128                69.002548            0.892395   -0.101103
130                66.505341            0.623278   -0.169091

     perception_of_corruption                 world_region  \
3                    0.842010  Latin America and Caribbean
13                   0.822606  Latin America and Caribbean
15                   0.770601  Latin America and Caribbean
23                   0.838239  Latin America and Caribbean
25                   0.864572  Latin America and Caribbean
27                   0.786332  Latin America and Caribbean
32                   0.756000  Latin America and Caribbean
33                   0.801215  Latin America and Caribbean
35                   0.754320  Latin America and Caribbean
45                   0.783237  Latin America and Caribbean
47                   0.684767  Latin America and Caribbean
48                   0.801132  Latin America and Caribbean
58                   0.888890  Latin America and Caribbean
81                   0.806822  Latin America and Caribbean
89                   0.665950  Latin America and Caribbean
94                   0.851589  Latin America and Caribbean
95                   0.834789  Latin America and Caribbean
96                   0.893715  Latin America and Caribbean
128                  0.635994  Latin America and Caribbean
130                  0.837038  Latin America and Caribbean

           country_name     area  population literacy
3             argentina  2766890    39921833     97,1
13              bolivia  1098580     8989046     87,2
15               brazil  8511965   188078227     86,4
23                chile   756950    16134219     96,2
25             colombia  1138910    43593035     92,5
27           costa rica    51100     4075261     96,0
32   dominican republic    48730     9183984     84,7
33              ecuador   283560    13547510     92,5
35          el salvador    21040     6822378     80,2
45            guatemala   108890    12293545     70,6
47                haiti    27750     8308504     52,9
48             honduras   112090     7326496     76,2
58              jamaica    10991     2758124     87,9
81               mexico  1972550   107449525     92,2
89            nicaragua   129494     5570129     67,5
94               panama    78200     3191319     92,6
95             paraguay   406750     6506464     94,0
96                 peru  1285220    28302603     90,9
128             uruguay   176220     3431932     98,0
130           venezuela   912050    25730435     93,4
world_region Middle East and North Africa
country                   country  happiness_score  social_support  \
2                 Algeria           5.0051        0.803385
8                 Bahrain           6.2273        0.876342
34                  Egypt           4.1514        0.735448
53                   Iran           4.6724        0.694690
54                   Iraq           4.7848        0.747695
56                 Israel           7.1286        0.913571
60                 Jordan           4.6334        0.802164
63                 Kuwait           6.1021        0.846475
67                Lebanon           4.7715        0.824338
70                  Libya           5.4888        0.825943
84                Morocco           5.0948        0.592628
103          Saudi Arabia           6.4065        0.874067
120               Tunisia           4.3922        0.688719
121                Turkey           5.1318        0.826314
125  United Arab Emirates           6.7908        0.849181
132                 Yemen           3.5274        0.817981

     healthy_life_expectancy  freedom_of_choices  generosity  \
2                  65.905174            0.466611   -0.121105
8                  68.500000            0.905856    0.133729
34                 61.780151            0.708354   -0.196878
53                 66.006149            0.647873    0.117891
54                 59.903549            0.633183   -0.069565
56                 73.200256            0.747581    0.102594
60                 66.799751            0.751048   -0.162565
63                 66.767647            0.872366   -0.100185
67                 67.106583            0.551358   -0.061215
70                 62.299999            0.773157   -0.085054
84                 65.896240            0.772072   -0.240377
103                66.305145            0.854191   -0.168695
120                66.897858            0.593362   -0.216414
121                66.902817            0.608830   -0.171046
125                67.082787            0.941346    0.123451
132                56.727283            0.599920   -0.157735

     perception_of_corruption                  world_region  \
2                    0.735485  Middle East and North Africa
8                    0.739347  Middle East and North Africa
34                   0.787727  Middle East and North Africa
53                   0.714636  Middle East and North Africa
54                   0.822262  Middle East and North Africa
56                   0.780855  Middle East and North Africa
60                   0.700344  Middle East and North Africa
63                   0.760849  Middle East and North Africa
67                   0.902256  Middle East and North Africa
70                   0.668779  Middle East and North Africa
84                   0.815725  Middle East and North Africa
103                  0.682620  Middle East and North Africa
120                  0.867590  Middle East and North Africa
121                  0.748197  Middle East and North Africa
125                  0.594502  Middle East and North Africa
132                  0.800288  Middle East and North Africa

             country_name     area  population literacy
2                 algeria  2381740    32930091     70,0
8                 bahrain      665      698585     89,1
34                  egypt  1001450    78887007     57,7
53                   iran  1648000    68688433     79,4
54                   iraq   437072    26783383     40,4
56                 israel    20770     6352117     95,4
60                 jordan    92300     5906760     91,3
63                 kuwait    17820     2418393     83,5
67                lebanon    10400     3874050     87,4
70                  libya  1759540     5900754     82,6
84                morocco   446550    33241259     51,7
103          saudi arabia  1960582    27019731     78,8
120               tunisia   163610    10175014     74,2
121                turkey   780580    70413958     86,5
125  united arab emirates    82880     2602713     77,9
132                 yemen   527970    21456188     50,2
world_region North America and ANZ
country            country  happiness_score  social_support  healthy_life_expectancy  \
5        Australia           7.2228        0.944855                73.604538
21          Canada           7.2321        0.927177                73.601601
88     New Zealand           7.2996        0.949119                73.202629
127  United States           6.9396        0.914219                68.299500

     freedom_of_choices  generosity  perception_of_corruption  \
5              0.915432    0.190460                  0.415169
21             0.933913    0.124771                  0.390843
88             0.936217    0.191598                  0.221139
127            0.842620    0.149892                  0.699715

              world_region   country_name     area  population literacy
5    North America and ANZ      australia  7686850    20264082    100,0
21   North America and ANZ         canada  9984670    33098932     97,0
88   North America and ANZ    new zealand   268680     4076140     99,0
127  North America and ANZ  united states  9631420   298444215     97,0
world_region South Asia
country          country  happiness_score  social_support  healthy_life_expectancy  \
0    Afghanistan           2.5669        0.470367                52.590000
9     Bangladesh           4.8328        0.687293                64.503067
51         India           3.5733        0.592201                60.215187
86         Nepal           5.1372        0.785512                63.779179
93      Pakistan           5.6933        0.689062                58.253136
112    Sri Lanka           4.3270        0.825374                67.200066

     freedom_of_choices  generosity  perception_of_corruption world_region  \
0              0.396573   -0.096429                  0.933687   South Asia
9              0.900625   -0.033665                  0.661844   South Asia
51             0.881445    0.057552                  0.772043   South Asia
86             0.797565    0.154169                  0.738099   South Asia
93             0.734834    0.044900                  0.745705   South Asia
112            0.837634    0.081130                  0.859002   South Asia

    country_name     area  population literacy
0    afghanistan   647500    31056997     36,0
9     bangladesh   144000   147365352     43,1
51         india  3287590  1095351995     59,5
86         nepal   147181    28287147     45,2
93      pakistan   803940   165803560     45,7
112    sri lanka    65610    20222240     92,3
world_region Southeast Asia
country          country  happiness_score  social_support  healthy_life_expectancy  \
19      Cambodia           4.8484        0.773081                61.529968
52     Indonesia           5.2856        0.808380                62.155849
65          Laos           4.8886        0.737502                58.709923
76      Malaysia           5.3843        0.816509                67.102158
97   Philippines           6.0060        0.846730                61.926762
107    Singapore           6.3771        0.910269                76.804581
118     Thailand           5.9988        0.889973                67.250595
131      Vietnam           5.3535        0.849987                67.952736

     freedom_of_choices  generosity  perception_of_corruption    world_region  \
19             0.959705    0.051911                  0.822769  Southeast Asia
52             0.870614    0.519587                  0.876296  Southeast Asia
65             0.907214    0.111371                  0.634679  Southeast Asia
76             0.894627    0.114727                  0.839302  Southeast Asia
97             0.915463   -0.105463                  0.733634  Southeast Asia
107            0.926645    0.029879                  0.109784  Southeast Asia
118            0.905063    0.268685                  0.886272  Southeast Asia

The first region has only a few countries! What are them and what is their score?

In [56]:
# Write your code here
hej = merged_df[(merged_df['world_region'] == 'East Asia')]
hej[['world_region', 'country', 'happiness_score' ]]

   world_region   country  happiness_score
24    East Asia     China           5.1239
59    East Asia     Japan           5.8708
83    East Asia  Mongolia           5.4562

## Task 4: How literate is the world?

Print the name of countries with a level of literacy of 100%. 

For each country, print the name and the world region with the format: *{region name} - {country name} ({happiness score})*

In [ ]:
# Write your code here

What is the global average?

In [ ]:
# Write your code here

Calculate the proportion of countries with a literacy level below 50%. Print the value in percentage, formatted with 2 decimals.

In [ ]:
# Write your code here

Print the raw number and the percentage of world population that is illiterate.

In [ ]:
# Write your code here

## Task 5: Population density

Add to the dataframe a new field called *population_density* computed by dividing *population* by *area*.

In [ ]:
# Write your code here

What is the happiness score of the 3 countries with lowest population density?

In [ ]:
# Write your code here

## Task 6: Healty and happy?

Plot in scatter plot the happiness score (x) and healty like expectancy (y).

In [ ]:
# Write your code here

Feel free to continue the exploration of the dataset! We'll release the solutions next week.

----
Enjoy EPFL and be happy, next year Switzerland must be #1.